//! The macOS packaging scripts are destructive and have no CI behind them.
//!
//! `.github/workflows/windows.yml` smoke-tests the Windows installer end to end on every
//! run; there is no macOS workflow at all, so the `preinstall` sweep generated by
//! `scripts/release.sh` — which `rm -rf`s out of `/Library` and every real user's
//! `~/Library` — and `scripts/uninstall-macos.sh` would otherwise ship having never run
//! anywhere but a real machine during a real install.
//!
//! The sweep is fully sandboxable: every path it builds derives from `$3`, the destination
//! volume, so pointing that at a scratch tree contains it completely. The uninstaller is
//! not — its paths are absolute — so it is driven through `PATH` stubs instead.
#![cfg(target_os = "macos")]

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// A fixed, named scratch root — not randomized, so a failure is inspectable afterwards.
/// Each test uses its own name: cargo runs them in parallel threads within one binary.
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(name);
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("could not create the scratch root");
    // Resolve symlinks: /tmp is a link to /private/tmp, and the guard below compares
    // against std::env::temp_dir(), which reports the unresolved form.
    dir.canonicalize().unwrap_or(dir)
}

/// Stamp a preinstall exactly the way `make_scripts()` in `scripts/release.sh` does:
/// a shebang, three unquoted variable assignments, then `packaging/macos/preinstall.in`
/// verbatim. Driving the same template the release stamps is the whole point — a copy of
/// the body pasted in here would pass forever while the shipped one rotted.
fn stamp_preinstall(dir: &Path, subdir: &str, bundle: &str, clear_au_cache: u8) -> PathBuf {
    let template = std::fs::read_to_string(repo_root().join("packaging/macos/preinstall.in"))
        .expect("packaging/macos/preinstall.in is missing — did make_scripts stop using it?");
    let script = dir.join("preinstall");
    std::fs::write(
        &script,
        format!("#!/bin/sh\nSUBDIR={subdir}\nBUNDLE={bundle}\nCLEAR_AU_CACHE={clear_au_cache}\n{template}"),
    )
    .expect("could not write the stamped preinstall");
    script
}

/// Run a stamped preinstall against a scratch volume.
///
/// The guard is not decorative. `VOL=${3:-/}` collapses "/" and an absent argument to the
/// empty string, i.e. the real boot volume — so a bug in a *test* that passed "" or "/"
/// here would delete every ConjureAlign install on the developer's machine, and with a
/// broken `case` guard, every plug-in of that format by any vendor.
fn run_preinstall(script: &Path, vol: &Path) -> Output {
    let vol_str = vol.to_str().expect("scratch path is not UTF-8");
    // Both sides canonicalized: on macOS temp_dir() reports /var/folders/... while a
    // resolved scratch path is /private/var/folders/..., and an unresolved comparison
    // would reject every legitimate call.
    let tmp = std::env::temp_dir();
    let tmp = tmp.canonicalize().unwrap_or(tmp);
    assert!(
        vol_str.len() > 1 && vol.is_absolute() && vol.starts_with(&tmp),
        "refusing to run the sweep against {vol_str:?} — it must be an absolute path under \
         the temp dir, or this test would sweep the real machine"
    );
    Command::new("/bin/sh")
        .arg(script)
        .args(["", "", vol_str])
        .output()
        .expect("could not run the stamped preinstall")
}

/// The home directories the sweep will actually visit.
///
/// `dscl` reads the *booted* system's directory regardless of `$3`, so the per-user half of
/// the sweep lands at `<scratch><real home>/Library/...`. Rather than fake `dscl`, ask it
/// the same question the script does and plant fixtures where the answer says they'll land.
fn swept_user_homes() -> Vec<PathBuf> {
    let out = Command::new("dscl")
        .args([".", "-list", "/Users", "NFSHomeDirectory"])
        .output()
        .expect("could not run dscl");
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .filter_map(|line| {
            let mut parts = line.split_whitespace();
            let user = parts.next()?;
            let home = line[user.len()..].trim();
            if user.starts_with('_') || !home.starts_with("/Users/") {
                return None;
            }
            Some(PathBuf::from(home))
        })
        .collect()
}

/// A plug-in bundle is a directory; plant a file inside so an `rm -rf` is distinguishable
/// from an `rmdir`.
fn plant_bundle(path: &Path) {
    std::fs::create_dir_all(path).expect("could not create a fixture bundle");
    std::fs::write(path.join("Contents"), b"payload").expect("could not fill a fixture bundle");
}

/// Plant the full three-format tree, plus another vendor's bundle and an AU cache, under
/// `vol` — in the system domain and in every home the sweep will visit.
fn plant_tree(vol: &Path) {
    let mut roots = vec![vol.join("Library")];
    for home in swept_user_homes() {
        // `home` is absolute; the script concatenates it onto $VOL, so strip the leading /.
        roots.push(vol.join(home.strip_prefix("/").unwrap()).join("Library"));
    }
    for root in roots {
        let plugins = root.join("Audio/Plug-Ins");
        plant_bundle(&plugins.join("VST3/ConjureAlign.vst3"));
        plant_bundle(&plugins.join("CLAP/ConjureAlign.clap"));
        plant_bundle(&plugins.join("Components/ConjureAlign.component"));
        plant_bundle(&plugins.join("VST3/SomeoneElse.vst3"));
        // Directly under Plug-Ins, in no format subdirectory. This is the path an empty
        // $SUBDIR collapses to — "$1/$SUBDIR/$BUNDLE" becomes "$1//ConjureAlign.vst3",
        // and the doubled slash resolves — so it is what makes the emptiness guard
        // observable. A correct sweep never touches it.
        plant_bundle(&plugins.join("ConjureAlign.vst3"));
        plant_bundle(&root.join("Caches/AudioUnitCache"));
    }
}

/// Every path the sweep could touch, as (path, label) pairs, across all swept domains.
fn all_targets(vol: &Path, relative: &str) -> Vec<PathBuf> {
    let mut out = vec![vol.join("Library").join(relative)];
    for home in swept_user_homes() {
        out.push(
            vol.join(home.strip_prefix("/").unwrap())
                .join("Library")
                .join(relative),
        );
    }
    out
}

#[track_caller]
fn assert_all_gone(vol: &Path, relative: &str) {
    for p in all_targets(vol, relative) {
        assert!(!p.exists(), "{} should have been swept, but it is still there", p.display());
    }
}

#[track_caller]
fn assert_all_survive(vol: &Path, relative: &str) {
    for p in all_targets(vol, relative) {
        assert!(p.exists(), "{} should have survived the sweep, but it is gone", p.display());
    }
}

#[track_caller]
fn assert_clean_exit(out: &Output) {
    // A non-zero preinstall aborts the whole installation, so this matters as much as the
    // filesystem effects — including on the no-op paths.
    assert!(
        out.status.success(),
        "the preinstall exited {:?}\nstdout: {}\nstderr: {}",
        out.status.code(),
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );
}

#[test]
fn the_vst3_sweep_takes_the_vst3_bundle_and_nothing_else() {
    let vol = scratch("conjure-align-pkg-sweep-vst3");
    plant_tree(&vol);

    let out = run_preinstall(&stamp_preinstall(&vol, "VST3", "ConjureAlign.vst3", 0), &vol);
    assert_clean_exit(&out);

    assert_all_gone(&vol, "Audio/Plug-Ins/VST3/ConjureAlign.vst3");
    // The other two formats are installed by their own packages, whose own preinstalls
    // sweep them. This one must not reach across.
    assert_all_survive(&vol, "Audio/Plug-Ins/CLAP/ConjureAlign.clap");
    assert_all_survive(&vol, "Audio/Plug-Ins/Components/ConjureAlign.component");
    // Another vendor's plug-in in the very same directory.
    assert_all_survive(&vol, "Audio/Plug-Ins/VST3/SomeoneElse.vst3");
    // Only the AU package clears the cache.
    assert_all_survive(&vol, "Caches/AudioUnitCache");
}

#[test]
fn only_the_au_sweep_clears_the_audio_unit_cache() {
    let vol = scratch("conjure-align-pkg-sweep-au");
    plant_tree(&vol);

    let out = run_preinstall(
        &stamp_preinstall(&vol, "Components", "ConjureAlign.component", 1),
        &vol,
    );
    assert_clean_exit(&out);

    assert_all_gone(&vol, "Audio/Plug-Ins/Components/ConjureAlign.component");
    assert_all_survive(&vol, "Audio/Plug-Ins/VST3/ConjureAlign.vst3");
    assert_all_survive(&vol, "Audio/Plug-Ins/CLAP/ConjureAlign.clap");
    assert_all_survive(&vol, "Audio/Plug-Ins/VST3/SomeoneElse.vst3");

    // The system-domain cache is deliberately not touched — the removal sits inside the
    // per-user loop — so assert on the user homes only.
    for home in swept_user_homes() {
        let cache = vol
            .join(home.strip_prefix("/").unwrap())
            .join("Library/Caches/AudioUnitCache");
        assert!(!cache.exists(), "{} should have been cleared", cache.display());
    }
}

#[test]
fn an_empty_subdir_or_bundle_deletes_nothing() {
    // The generated script runs with no `set -u`, so a variable that failed to stamp must
    // not reach the rm. Both halves of `[ -n "$SUBDIR" ] && [ -n "$BUNDLE" ]` get a case.
    //
    // Only the $SUBDIR half is independently observable: an empty $BUNDLE is *also*
    // rejected by the `case "$BUNDLE" in ConjureAlign.*` guard below it, so that half
    // stays covered even with this guard deleted, and it only bites when both are gone —
    // which is the point of having two. Verified by mutation, 2026-09-02.
    for (i, (subdir, bundle)) in [("", "ConjureAlign.vst3"), ("VST3", "")].iter().enumerate() {
        let vol = scratch(&format!("conjure-align-pkg-sweep-empty-{i}"));
        plant_tree(&vol);

        let out = run_preinstall(&stamp_preinstall(&vol, subdir, bundle, 0), &vol);
        assert_clean_exit(&out);

        // The one an empty $SUBDIR would reach.
        assert_all_survive(&vol, "Audio/Plug-Ins/ConjureAlign.vst3");
        assert_all_survive(&vol, "Audio/Plug-Ins/VST3/ConjureAlign.vst3");
        assert_all_survive(&vol, "Audio/Plug-Ins/CLAP/ConjureAlign.clap");
        assert_all_survive(&vol, "Audio/Plug-Ins/Components/ConjureAlign.component");
        assert_all_survive(&vol, "Audio/Plug-Ins/VST3/SomeoneElse.vst3");
        assert_all_survive(&vol, "Caches/AudioUnitCache");
    }
}

#[test]
fn a_bundle_that_is_not_ours_is_never_deleted() {
    // Pins `case "$BUNDLE" in ConjureAlign.*)`. Without it, a mis-stamped package would
    // delete another vendor's plug-in.
    let vol = scratch("conjure-align-pkg-sweep-notours");
    plant_tree(&vol);

    let out = run_preinstall(&stamp_preinstall(&vol, "VST3", "SomeoneElse.vst3", 0), &vol);
    assert_clean_exit(&out);

    assert_all_survive(&vol, "Audio/Plug-Ins/VST3/SomeoneElse.vst3");
    assert_all_survive(&vol, "Audio/Plug-Ins/VST3/ConjureAlign.vst3");
}

#[test]
fn a_broken_symlink_at_the_target_is_still_removed() {
    // A dangling link is what a half-removed hand-install leaves behind, and it is exactly
    // what `-e` alone would miss — hence the `[ -L "$t" ]` arm.
    let vol = scratch("conjure-align-pkg-sweep-symlink");
    let plugins = vol.join("Library/Audio/Plug-Ins/VST3");
    std::fs::create_dir_all(&plugins).unwrap();
    let link = plugins.join("ConjureAlign.vst3");
    std::os::unix::fs::symlink(vol.join("nowhere"), &link).unwrap();
    assert!(!link.exists(), "the fixture should be a DANGLING symlink");
    assert!(link.symlink_metadata().is_ok(), "the fixture link should exist");

    let out = run_preinstall(&stamp_preinstall(&vol, "VST3", "ConjureAlign.vst3", 0), &vol);
    assert_clean_exit(&out);

    assert!(
        link.symlink_metadata().is_err(),
        "the dangling symlink should have been swept, but it is still there"
    );
}

// ---------------------------------------------------------------------------
// scripts/uninstall-macos.sh
//
// Unlike the sweep, this script takes no destination volume — every path is an
// absolute constant, and its privileged phase would `rm -rf` the developer's real
// install. So it is exercised as a copy with those roots rebased onto a scratch tree,
// plus `PATH` stubs for the four external commands it shells out to.
//
// A rebased copy only tests anything as long as the rebase still matches, so every
// replacement below asserts it found exactly one occurrence: rename a constant in the
// shipped script and this fails loudly rather than testing a script nobody ships.
// ---------------------------------------------------------------------------

/// The literals `rebase()` rewrites, as (needle, replacement-template) with `{root}`
/// standing in for the scratch root.
const REBASES: &[(&str, &str)] = &[
    (
        r#"INSTALL_DIR="/Applications/ConjureDSP""#,
        r#"INSTALL_DIR="{root}/Applications/ConjureDSP""#,
    ),
    (
        r#"printf '/Library/Audio/Plug-Ins/%s/%s\n'"#,
        r#"printf '{root}/Library/Audio/Plug-Ins/%s/%s\n'"#,
    ),
    (
        r#"printf '%s/Library/Audio/Plug-Ins/%s/%s\n' "$h""#,
        r#"printf '{root}%s/Library/Audio/Plug-Ins/%s/%s\n' "$h""#,
    ),
    (
        r#"rm -rf "$h/Library/Caches/AudioUnitCache""#,
        r#"rm -rf "{root}$h/Library/Caches/AudioUnitCache""#,
    ),
];

/// Write a copy of the uninstaller with its absolute roots rebased under `root`.
fn rebased_uninstaller(root: &Path, dest: &Path) -> PathBuf {
    let mut text = std::fs::read_to_string(repo_root().join("scripts/uninstall-macos.sh"))
        .expect("scripts/uninstall-macos.sh is missing");
    let root_str = root.to_str().unwrap();
    for (needle, replacement) in REBASES {
        assert_eq!(
            text.matches(needle).count(),
            1,
            "expected exactly one occurrence of {needle:?} in scripts/uninstall-macos.sh — \
             the script changed and this test is no longer rebasing what it thinks it is"
        );
        text = text.replace(needle, &replacement.replace("{root}", root_str));
    }
    std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
    std::fs::write(dest, text).expect("could not write the rebased uninstaller");
    Command::new("chmod").arg("755").arg(dest).status().unwrap();
    dest.to_path_buf()
}

/// A `bin/` of stubs for the commands the uninstaller shells out to, first on `PATH`.
///
/// `dscl` names a user that cannot exist, so any path this test failed to rebase lands
/// somewhere harmless instead of on a real home directory.
const STUB_USER_HOME: &str = "/Users/conjure-align-test-nobody";

fn stub_bin(root: &Path) -> PathBuf {
    let bin = root.join("stub-bin");
    std::fs::create_dir_all(&bin).unwrap();
    let stubs = [
        ("sudo", "#!/bin/sh\nexec \"$@\"\n".to_string()),
        (
            "dscl",
            format!("#!/bin/sh\nprintf 'conjure-align-test-nobody\\t{STUB_USER_HOME}\\n'\n"),
        ),
        // --pkg-info exits non-zero: no receipts are registered for a scratch tree.
        ("pkgutil", "#!/bin/sh\nexit 1\n".to_string()),
        ("killall", "#!/bin/sh\nexit 0\n".to_string()),
    ];
    for (name, body) in stubs {
        let p = bin.join(name);
        std::fs::write(&p, body).unwrap();
        Command::new("chmod").arg("755").arg(&p).status().unwrap();
    }
    bin
}

fn run_uninstaller(script: &Path, root: &Path, home: &Path, args: &[&str]) -> Output {
    Command::new("/bin/sh")
        .arg(script)
        .args(args)
        .env("PATH", format!("{}:/usr/bin:/bin:/usr/sbin:/sbin", stub_bin(root).display()))
        .env("HOME", home)
        .output()
        .expect("could not run the rebased uninstaller")
}

#[test]
fn the_shared_conjuredsp_directory_is_rmdired_never_rm_rfed() {
    // /Applications/ConjureDSP is shared with every other ConjureDSP product's
    // uninstaller. Removing it recursively would take a sibling product's uninstaller
    // with it, so it goes only when already empty.
    let root = scratch("conjure-align-uninstall-shared-dir");
    let home = root.join("home");
    let install_dir = root.join("Applications/ConjureDSP");
    let script = rebased_uninstaller(&root, &install_dir.join("Uninstall ConjureAlign.command"));
    let sibling = install_dir.join("Uninstall ConjureOther.command");
    std::fs::write(&sibling, b"another product").unwrap();

    let out = run_uninstaller(&script, &root, &home, &["--privileged-phase"]);
    assert_clean_exit(&out);

    assert!(!script.exists(), "the uninstaller should have removed itself");
    assert!(sibling.exists(), "another ConjureDSP product's uninstaller was deleted");
    assert!(install_dir.exists(), "{} was removed even though it still had contents", install_dir.display());
}

#[test]
fn the_directory_goes_only_once_it_is_empty() {
    // The other half of the same rmdir: with nothing else left, it should be cleaned up
    // rather than lingering forever.
    let root = scratch("conjure-align-uninstall-empty-dir");
    let home = root.join("home");
    let install_dir = root.join("Applications/ConjureDSP");
    let script = rebased_uninstaller(&root, &install_dir.join("Uninstall ConjureAlign.command"));

    let out = run_uninstaller(&script, &root, &home, &["--privileged-phase"]);
    assert_clean_exit(&out);

    assert!(!script.exists(), "the uninstaller should have removed itself");
    assert!(!install_dir.exists(), "{} should have been rmdir'd once empty", install_dir.display());
}

#[test]
fn a_copy_run_from_outside_the_install_location_never_deletes_itself() {
    // Pins `case "$SELF" in "$INSTALL_DIR"/*)`. Without it, running the script from a
    // source checkout would delete the checkout's copy.
    let root = scratch("conjure-align-uninstall-outside");
    let home = root.join("home");
    let script = rebased_uninstaller(&root, &root.join("checkout/uninstall-macos.sh"));

    let out = run_uninstaller(&script, &root, &home, &["--privileged-phase"]);
    assert_clean_exit(&out);

    assert!(script.exists(), "a copy run from outside the install location deleted itself");
}

#[test]
fn the_privileged_phase_removes_installed_bundles_and_the_au_cache() {
    let root = scratch("conjure-align-uninstall-bundles");
    let home = root.join("home");
    let script = rebased_uninstaller(&root, &root.join("checkout/uninstall-macos.sh"));

    // System domain, plus the stub user's home, plus another vendor's plug-in.
    let sys = root.join("Library/Audio/Plug-Ins");
    let usr = root
        .join(STUB_USER_HOME.strip_prefix('/').unwrap())
        .join("Library/Audio/Plug-Ins");
    for plugins in [&sys, &usr] {
        plant_bundle(&plugins.join("VST3/ConjureAlign.vst3"));
        plant_bundle(&plugins.join("CLAP/ConjureAlign.clap"));
        plant_bundle(&plugins.join("Components/ConjureAlign.component"));
        plant_bundle(&plugins.join("VST3/SomeoneElse.vst3"));
    }
    let cache = root
        .join(STUB_USER_HOME.strip_prefix('/').unwrap())
        .join("Library/Caches/AudioUnitCache");
    plant_bundle(&cache);

    let out = run_uninstaller(&script, &root, &home, &["--privileged-phase"]);
    assert_clean_exit(&out);

    for plugins in [&sys, &usr] {
        for gone in [
            "VST3/ConjureAlign.vst3",
            "CLAP/ConjureAlign.clap",
            "Components/ConjureAlign.component",
        ] {
            assert!(!plugins.join(gone).exists(), "{gone} should have been removed");
        }
        assert!(
            plugins.join("VST3/SomeoneElse.vst3").exists(),
            "another vendor's plug-in was removed"
        );
    }
    assert!(!cache.exists(), "the AU cache should have been cleared");
}

#[test]
fn only_the_conjurealign_child_of_the_settings_directory_is_removed() {
    // The parent ~/Library/Application Support/ConjureDSP/ is shared with the ConjureDSP
    // app and every other ConjureDSP plug-in. Removing settings is irreversible — it
    // destroys the consent answers and the install id — so this is the single most
    // damaging thing the script can get wrong.
    let root = scratch("conjure-align-uninstall-settings");
    let home = root.join("home");
    let support = home.join("Library/Application Support/ConjureDSP");
    let ours = support.join("ConjureAlign");
    let theirs = support.join("ConjureDSP-App");
    plant_bundle(&ours);
    plant_bundle(&theirs);
    let script = rebased_uninstaller(&root, &root.join("checkout/uninstall-macos.sh"));

    // --yes and --remove-settings make phase 1 non-interactive; the stub `sudo` runs the
    // privileged phase for real against the rebased roots.
    let out = run_uninstaller(&script, &root, &home, &["--yes", "--remove-settings"]);
    assert_clean_exit(&out);

    assert!(!ours.exists(), "our settings directory should have been removed");
    assert!(theirs.exists(), "a sibling ConjureDSP product's data was removed");
    assert!(support.exists(), "the shared ConjureDSP support directory was removed");
}

#[test]
fn settings_survive_unless_removal_was_asked_for() {
    let root = scratch("conjure-align-uninstall-keep-settings");
    let home = root.join("home");
    let ours = home.join("Library/Application Support/ConjureDSP/ConjureAlign");
    plant_bundle(&ours);
    let script = rebased_uninstaller(&root, &root.join("checkout/uninstall-macos.sh"));

    let out = run_uninstaller(&script, &root, &home, &["--yes", "--keep-settings"]);
    assert_clean_exit(&out);

    assert!(ours.exists(), "settings were removed without --remove-settings");
}

// ---------------------------------------------------------------------------
// The duplicated user-home enumeration
//
// The sweep in packaging/macos/preinstall.in and user_homes() in
// scripts/uninstall-macos.sh each ask dscl the same question and apply the same two
// filters, and both carry a "KEEP IN SYNC" comment pointing at the other with nothing
// checking it. They are not textually identical — one falls through to a sweep, the
// other prints — so what is asserted here is the thing that actually has to match:
// given identical dscl output, both select exactly the same set of homes.
//
// Same spirit as the two drift guards that already exist: the receipt-id check in
// scripts/release.sh, and the uninstall GUID duplicated into windows.yml so that drift
// fails CI instead of silently breaking upgrades.
// ---------------------------------------------------------------------------

/// dscl rows covering both filters independently, plus the whitespace handling.
///
/// `_daemon` deliberately has a home *under /Users*: a service account parked at
/// /var/empty is rejected by the home filter as well, so it would leave the `_*` filter
/// untested — drop that filter and nothing would change. This row is rejected by the
/// account-name filter alone, which is what makes it observable.
const DSCL_ROWS: &[(&str, &str)] = &[
    ("_spotlight", "/var/empty"),
    ("_daemon", "/Users/_daemon"),
    ("netuser", "/Network/Servers/somewhere"),
    ("real", "/Users/real"),
    ("spacey", "/Users/with space"),
];

/// The homes both enumerations are expected to keep.
const EXPECTED_HOMES: &[&str] = &["/Users/real", "/Users/with space"];

fn dscl_stub(root: &Path) -> PathBuf {
    let bin = root.join("dscl-stub-bin");
    std::fs::create_dir_all(&bin).unwrap();
    let rows: String = DSCL_ROWS
        .iter()
        .map(|(u, h)| format!("printf '%s\\t%s\\n' '{u}' '{h}'\n"))
        .collect();
    let p = bin.join("dscl");
    std::fs::write(&p, format!("#!/bin/sh\n{rows}")).unwrap();
    Command::new("chmod").arg("755").arg(&p).status().unwrap();
    bin
}

/// Pull one `name() { ... }` function out of a shell script, by brace column.
fn extract_shell_function(text: &str, name: &str) -> String {
    let open = format!("{name}() {{");
    let start = text
        .find(&open)
        .unwrap_or_else(|| panic!("no function {name}() in the script — it was renamed?"));
    let rest = &text[start..];
    let end = rest
        .find("\n}\n")
        .unwrap_or_else(|| panic!("could not find the end of {name}()"));
    rest[..end + 3].to_string()
}

#[test]
fn the_two_user_home_enumerations_select_the_same_homes() {
    let root = scratch("conjure-align-user-homes");
    let stub_path = format!("{}:/usr/bin:/bin", dscl_stub(&root).display());

    // --- side 1: user_homes() from the uninstaller, called directly ---
    let uninstaller = std::fs::read_to_string(repo_root().join("scripts/uninstall-macos.sh"))
        .expect("scripts/uninstall-macos.sh is missing");
    let func = extract_shell_function(&uninstaller, "user_homes");
    let probe = root.join("user_homes_probe.sh");
    std::fs::write(&probe, format!("{func}\nuser_homes\n")).unwrap();
    let out = Command::new("/bin/sh")
        .arg(&probe)
        .env("PATH", &stub_path)
        .output()
        .expect("could not run the user_homes probe");
    assert_clean_exit(&out);
    let from_uninstaller: Vec<String> = String::from_utf8_lossy(&out.stdout)
        .lines()
        .map(str::to_string)
        .collect();

    assert_eq!(
        from_uninstaller, EXPECTED_HOMES,
        "user_homes() in scripts/uninstall-macos.sh selected an unexpected set of homes"
    );

    // --- side 2: the sweep, observed by which planted bundles it actually removes ---
    let vol = root.join("vol");
    std::fs::create_dir_all(&vol).unwrap();
    for (_, home) in DSCL_ROWS {
        plant_bundle(
            &vol.join(home.strip_prefix('/').unwrap())
                .join("Library/Audio/Plug-Ins/VST3/ConjureAlign.vst3"),
        );
    }
    let script = stamp_preinstall(&root, "VST3", "ConjureAlign.vst3", 0);
    let out = Command::new("/bin/sh")
        .arg(&script)
        .args(["", "", vol.to_str().unwrap()])
        .env("PATH", &stub_path)
        .output()
        .expect("could not run the stamped preinstall");
    assert_clean_exit(&out);

    let mut from_sweep: Vec<String> = DSCL_ROWS
        .iter()
        .filter(|(_, home)| {
            !vol.join(home.strip_prefix('/').unwrap())
                .join("Library/Audio/Plug-Ins/VST3/ConjureAlign.vst3")
                .exists()
        })
        .map(|(_, home)| home.to_string())
        .collect();
    from_sweep.sort();

    let mut expected = from_uninstaller.clone();
    expected.sort();
    assert_eq!(
        from_sweep, expected,
        "the preinstall sweep and user_homes() in scripts/uninstall-macos.sh no longer \
         visit the same home directories — the two KEEP IN SYNC blocks have drifted"
    );
}
